exclude = [
    "__pycache__",
    ".container_volumes",
    ".venv",
]

target-version = "py313"
line-length = 88

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false